config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  resources :users

	root 'simple_pages#landing_page'

  get 'simple_pages/index'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/press'

  post 'simple_pages/thank_you'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user
	belongs_to :category
	  has_attached_file :image, styles: { large: "900x900>", medium: "300x300>", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
	  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	def self.search(search_term)
		like_string = Rails.env.production? ? "ilike" : "LIKE"
		Post.where("content #{like_string} ?", "%#{search_term}%")
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :comments
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  redirect_to main_app.root_url, alert: exception.message
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    
  # @comment = Comment.new(comment_params)

  #  respond_to do |format|
  #    if @comment.save
  #      format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
  #      format.json { render :show, status: :created, location: @comment }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @comment.errors, status: :unprocessable_entity }
   #   end
  #  end

  @post = Post.find(params[:post_id])
  @comment = @post.comments.new(comment_params)
  @comment.user = current_user
  @comment.save
  p @comment.errors
  redirect_to post_path(@post)
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :user_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  # GET /posts
  # GET /posts.json
  def index
    if params[:q]
      search_term = params[:q]
      @posts = Post.search(search_term)
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.find(params[:id])
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        p @post.errors
        format.html { render :new}
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :category_id, :image)
    end

    def find_post
     @post = Post.find(params[:id])
end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController

	def landing_page
		@posts = Post.limit(4).order("created_at DESC")
    
	end

  def index
  end

  def about
  end

  def contact
  end

  def press
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, id: :comment_post_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SETI</title>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<div class="container-fluid">
  		<header>
        <div class="row justify-content-end">
          <div class="col-md-4 col-sm-4">
            <div class="navbar-form search_bar">
              <%= form_with(url: posts_path, method: 'get', local: true) do |form| %>
                <%= form.label :q, 'Search the blog', class: 'search-label' %>
                <%= form.text_field :q, id: 'q', value: params[:q], class: 'search-field' %>
                <%= form.submit 'Search', class: 'search-submit' %>
              <% end %>
            </div>
            
              <ul class="Btn-log pull-right">
                <li>
                  <% if user_signed_in? %>
                    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
                  <% else %>
                    <%= link_to('Login', new_user_session_path) %>
                  <% end %>
                </li>
              </ul>
           
          </div>
        </div>
  		</header><!-- end HEADER -->
  		<nav class="navbar navbar-expand-sm">
        <div class ="d-inline-flex">
    			<ul class="nav flex-column flex-sm-row">
    				<li class="nav-item p-2 dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Business</a>
                <ul class="dropdown-menu">
                  <li class="dropdown-item"><a href="#">She Made It!</a></li>
                  <li class="dropdown-item"><a href="#">Woman of The Month</a></li>
                  <li class="dropdown-item"><a href="#">Boost Your Career</a></li> 
                </ul>
            </li>

    				<li class="nav-item p-2 dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Style</a>
                <ul class="dropdown-menu" role="menu">
                  <li class="dropdown-item"><a href="#">Beauty</a></li>
                  <li class="dropdown-item"><a href="#">Fashion</a></li>
                  <li class="dropdown-item"><a href="#">Personal Development</a></li> 
                </ul>
            </li>

    				<li class="nav-item p-2 dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Culture</a>
              <ul class="dropdown-menu">
                <li class="dropdown-item"><a href="#">Did You Know?</a></li>
                <li class="dropdown-item"><a href="#">Travel</a></li>
                <li class="dropdown-item"><a href="#">TBD</a></li> 
              </ul>
            </li>
          </ul>
          <%= image_tag("seti.png", :class => 'logo-item') %>
          <ul class="nav flex-column flex-sm-row justify-content-end">
      			<li class="nav-item p-2">
              <%= link_to "Home", root_path, class:'nav-link' %>
            </li>
      			<li class="nav-item p-2">
              <%= link_to "About", simple_pages_about_path, class:'nav-link' %>
              </li>
      			<li class="nav-item p-2">
              <%= link_to "Contact", simple_pages_contact_path, class:'nav-link' %>
            </li>
    			</ul>
        </div>
			</nav><!-- end NAV -->
      
	<main>
    <p class="notice"><%= notice %></p>
  <%= yield %>
  </main>

  		<footer class="footer">
    	<p class="footer">&copy; 2017 Seti Austria</p>
  		</footer>
		</div>
	</body>
</html>

app/views/posts/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, html: { multipart: true }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :title, id: :post_category %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_new_comment.html.erb
<% if signed_in? %>
  <h4>Leave a Comment:</h4>
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <% f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p> 
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/posts/categories.html.erb
<h1>all</h1>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<main class="posts-index">


<h1>Posts</h1>
<p id="notice"><%= notice %></p>
<table class="post-table">
  <thead>
    <tr>

      <th>Category</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="post-form">
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-md-3">
          <tr>
            <td><%= post.category.name %></td>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td><%= link_to 'Show', post %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        </div><!-- Col -->
      <% end %>
    </div><!-- row -->
  </tbody>
</table>
<br>
<%= link_to 'New Post', new_post_path %>
</main>

app/views/posts/new.html.erb
<div class= "new-posts">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<!-- Page Content -->
    <div class="container show-container">
      <p id="notice"><%= notice %></p>
      <div class="row show-post justify-content-center">

        <!-- Post Content Column -->
        <div class="col col-lg-10">
          <div class="show-introduction">


          <!-- Title -->
          <h1 class="mt-4"><%= @post.title %></h1>

          <hr>

          <!-- Date/Time -->
          <p class="show-time-date">Posted on January 1, 2017 at 12:00 PM</p>

          <!-- Author -->
           <p class="lead">
            by<a href="#">Rachel Akilimali</a>
          </p>

          <hr>
        </div>
        <div class="show-image">
          <!-- Preview Image -->
         <p class="show-img"><%= image_tag @post.image.url(:large, class: "img-responsive") %></p>
       </div>
          <hr>

          <!-- Post Content -->
          <p class="lead exerpt">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

          <p class="show-post-content"><%= @post.content %>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

          <p class="show-post-content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          </blockquote>

          <p class="show-post-content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

          <p class="show-post-content">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

          <hr>

          <!-- Comments Form -->
          <%= render 'new_comment' %>
          <%= render 'comments' %>
         
    </div>

app/views/simple_pages/about.html.erb
<h1>ABOUT SETI</h1>
<p>SETI is a non-profit organization aiming at promoting successful initiatives of African youth and diaspora. This association aims in particular at highlighting women of talents who are impacting their communities and beyond. <br>

The motto is to share, support each other and grow!! <br>

More than an association,<br>

- SETI advocates for talented young women who make a difference and who can be a source of inspiration. <br>

- SETI is also an invitation to rediscover and explore the continent through a variety of experiences and a new generation of bold young African women <br>

- SETI offers a unique opportunity to build bridges and break barriers. <br>

The purpose of this association is to celebrate African creativity and culture beyond the continent. It aims at promoting new faces of African women whose talent and achievements are contributing to a greater purpose. <br>

The association will bring together all communities of African descent living in Austria as well as local Austrian guests, with a strong multicultural dimension, bringing together publics of diverse cultural backgrounds. Indeed, SETI is a great opportunity to advocate cultural exchanges and a positive way of interacting with others. <br>

We are looking forward to introducing you to young African women with raw talent, originality, purpose and passion!</p>

app/views/simple_pages/contact.html.erb
<div class="container">
<h1 class="contact-prompt">Contact Us</h1>

<%= flash[:notice] %>

<%= form_with(url:"/simple_pages/thank_you", method: "post", local: true) do |form| %>
<div class="contact-form">
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter Name" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "Enter Email" %>
  </div>
  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_area :message, class: "form-control", placeholder: "Enter Message", rows: 5 %>
  </div>
</div>
<%= form.submit "Send", class: "form_label" %>
<% end %>
</div>

app/views/simple_pages/index.html.erb
<h1>BlogPost#index</h1>

<!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Post Title</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="#">Start Bootstrap</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <p>Posted on January 1, 2017 at 12:00 PM</p>

          <hr>

          <!-- Preview Image -->
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

          <hr>

          <!-- Post Content -->
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

          <hr>

          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>

          <!-- Single Comment -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <!-- Comment with nested comments -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

            </div>
          </div>

        </div>

app/views/users/edit.html.erb
<main class="user-edit">
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</main>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>